base_config: base_config_alex_new.yaml

base:
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
sae:
  layer: 25

training:
  dataset_path: /home/woody/b114cb/b114cb23/boxo/diffing_datasets_big/final_dataset_iteration_0_4/
  name: "Model_Diffing_M0_D4"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 5000000
  threshold_num_batches: 1
  num_batches_in_buffer: 10
  lr: 0.0001
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/SAE_2025_04_02_32_15360_25/sae_training_iter_0/final
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/Diffing Alpha Amylase Mixture 32/step_1c/M0_D4
  resuming: true
  n_iters: 20
  model_diffing: true