
base_config: base_config_alex_new.yaml
base:
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
  d_sae: 15360
  batch_size: 4096
  model_batch_size: 512 
  seq_len: 512

training:
  checkpoint_dir: 
  lr: 0.0003
  num_tokens: 200000000
  name: "sae_training_iter_2"
  threshold_compute_freq: 100
  threshold_num_batches: 20 
  num_batches_in_buffer: 5
  perf_log_freq: 100
  checkpoint_freq: 10000
  top_k: 32  
  top_k_aux: 512 
  aux_penalty: 0.031
  datset_path: /home/woody/b114cb/b114cb23/boxo/new_dataset_concat_train/
  
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/New_SAE/sae_training_iter_1_32/final
  resuming: true
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_training_iter_2_32
