  paths:
    model_path: /home/woody/b114cb/b114cb23/DPO_clean_amylase_run_SAPI_only_gerard/output_iteration1/
    sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/diffing_sapi_07_04/M1_D1/diffing/
    test_set_path: /home/woody/b114cb/b114cb23/boxo/new_dataset_eval/
    is_tokenized: true
    out_dir: /home/woody/b114cb/b114cb23/diffing_sapi_07_04/eval_SAEs_RL_1_brenda/

  samples: 1000

