  paths:
    model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
    sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/diffing_sapi_07_04/M0_D23/diffing/
    test_set_path: /home/woody/b114cb/b114cb23/boxo/new_dataset_eval/
    is_tokenized: true
    out_dir: /home/woody/b114cb/b114cb23/diffing_sapi_07_04/eval_SAEs_BM_23_brenda/

  samples: 1000

