    paths:
      model_path: /home/woody/b114cb/b114cb23/models/model-3.2.1.1/
      sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/noelia_ft_dms/diffing/
      top_features_path: /home/woody/b114cb/b114cb23/boxo/noelia_ft_dms/latent_scoring/latent_scoring_0/important_features/important_features_pos_M0_D0_98_0.02_ablation.pkl
      out_dir: /home/woody/b114cb/b114cb23/boxo/noelia_ft_dms/latent_scoring/latent_scoring_0/ablation_with_all/M0_D0_98_0.02
    label: 3.2.1.1
    model_iteration: 0
    data_iteration: 0
