
base_config: base_config_alex.yaml
base:
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
  d_sae: 10240
  batch_size: 4096
  model_batch_size: 512 
  seq_len: 512

training:
  checkpoint_dir: 
  lr: 0.001
  num_tokens: 200000000
  name: "sae_finetune_512_ctx"
  threshold_compute_freq: 100
  threshold_num_batches: 20 
  num_batches_in_buffer: 5
  perf_log_freq: 100
  checkpoint_freq: 10000
  top_k: 100  
  top_k_aux: 512 
  aux_penalty: 0.01
  datset_path: /home/woody/b114cb/b114cb23/boxo/new_dataset_train/
  
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/ZymCTRL_25_02_25_h100_blocks.26.hook_resid_pre_10240_batchtopk_100_0.0003_200000
  resuming: true
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_finetune_512_ctx
