_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.6
            "6": 4.49.0
            "8":
                - 5
                - 13
            "12": 0.19.6
            "13": linux-x86_64
act_size:
    value: 1280
aux_penalty:
    value: 0.03125
bandwidth:
    value: 0.001
batch_size:
    value: 512
beta1:
    value: 0.9
beta2:
    value: 0.99
checkpoint_dir:
    value: /users/nferruz/gboxo/ZymCTRL/
checkpoint_freq:
    value: 100000
dataset_path:
    value: /users/nferruz/gboxo/ZYN_CTRL_Dataset/dataset.arrow/
device:
    value: cuda
dict_size:
    value: 5120
dtype:
    value: torch.float32
hook_point:
    value: blocks.10.hook_resid_pre
input_unit_norm:
    value: true
l1_coeff:
    value: 0
layer:
    value: 10
lr:
    value: 0.0003
max_grad_norm:
    value: 100000
model_batch_size:
    value: 256
model_name:
    value: ProtGPT2
n_batches_to_dead:
    value: 20
name:
    value: ProtGPT2_blocks.10.hook_resid_pre_5120_batchtopk_32_0.0003
num_batches_in_buffer:
    value: 10
num_tokens:
    value: 1000000000
perf_log_freq:
    value: 1000
sae_type:
    value: batchtopk
seed:
    value: 49
seq_len:
    value: 256
site:
    value: resid_pre
top_k:
    value: 32
top_k_aux:
    value: 1024
wandb_project:
    value: protGPT_SAE
