  paths:
    model_path: /home/woody/b114cb/b114cb23/DPO_clean_amylase_run_SAPI_only_gerard/output_iteration12/
    sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/diffing_sapi_07_04/M12_D12/diffing/
    test_set_path: /home/woody/b114cb/b114cb23/boxo/diffing_sapi_07_04/diffing_sapi_07_04_dataset/diffing_datasets/dataset_iteration12/eval/
    is_tokenized: true
    out_dir: /home/woody/b114cb/b114cb23/diffing_sapi_07_04/eval_SAEs_RL_12_amylase/

  samples: 1000

