base_config: base_config_alex_new.yaml

base:
  model_path: /home/woody/b114cb/b114cb23/DPO_clean_amylase_run_SAPI_only_gerard/output_iteration15
sae:
  layer: 25

training:
  dataset_path: /home/woody/b114cb/b114cb23/boxo/diffing_sapi_multi_iterations_clean/dataset_iteration3/
  name: "Diffing_SAPI_M3_D3"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 150000
  threshold_num_batches: 5
  num_batches_in_buffer: 10
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/finetune_SAE_DMS/iteration16/diffing/
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/diffing_sapi_multi_iterations_clean/M3_D3_rl/
  resuming: true
  model_diffing: true
