
base_config: base_config_alex.yaml

training:
  num_tokens: 50000
  name: "sae_training_iter_2"
  checkpoint_dir: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_training_iter_2
  wandb_project: "DEBUG"

resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_training_iter_1/final
  resuming: true
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_training_iter_2

