base_config: base_config_alex_new.yaml

base:
  model_path: AI4PD/ZymCTRL
sae:
  layer: 25

training:
  dataset_path: /users/nferruz/gboxo/finetune_SAE_DMS/dataset/train/
  name: "Finetune_SAE_DMS"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 4000000
  threshold_num_batches: 5
  num_batches_in_buffer: 10
resuming:
  resume_from: /users/nferruz/gboxo/ZymCTRLSAEs/checkpoints/SAE_2025_04_02_32_15360_25/sae_training_iter_0/final
  checkpoint_dir_to: /users/nferruz/gboxo/ZymCTRLSAEs/checkpoints/finetune_SAE_DMS/
  resuming: true
  n_iters: 20
  model_diffing: true
