paths:
  seqs_path: "/home/woody/b114cb/b114cb23/boxo/strong_steering/seq_gen/seq_gen_3.2.1.1_1.2_ZC_FT.fasta"
  output_path: "/home/woody/b114cb/b114cb23/boxo/strong_steering/seq_gen/activity_predictions_1.2.csv"

  oracle_path1: "/home/woody/b114cb/b114cb23/models/esm2_t33_650M_UR50D"
  checkpoint_path1: "/home/woody/b114cb/b114cb23/Filippo/alpha_amylase_activity_predictor/LoRa_esm2_3B/esm_GB1_finetuned.pth"

  oracle_path2: "/home/woody/b114cb/b114cb23/models/esm1v_t33_650M_UR90S_1"
  checkpoint_path2: "/home/woody/b114cb/b114cb23/Filippo/alpha_amylase_activity_predictor/LoRA_esm1v/Esm1v_GB1_finetuned.pth"

label: 3.2.1.1
