paths:
  model_path: "/home/woody/b114cb/b114cb23/ZF_FT_alphaamylase_gerard/FT_3.2.1.1/"
  df_path: "/home/woody/b114cb/b114cb23/boxo/oracle_eval/activity_predictions2.csv"
  sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/strong_steering/diffing/
  top_features_path: ""
  out_dir: "/home/woody/b114cb/b114cb23/boxo/strong_steering/steering/M1_D1_pos_O2"

label: 3.2.1.1
model_iteration: 0 # 0
data_iteration: 0 # 0