base_config: base_config_alex_new.yaml

base:
  model_path: /home/woody/b114cb/b114cb23/models/model-3.2.1.1/
sae:
  layer: 15

training:
  dataset_path: /home/woody/b114cb/b114cb23/boxo/finetune_SAE_DMS/dataset/train/
  name: "Finetune_DMS_noelia_Ft"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 4000000
  threshold_num_batches: 5
  num_batches_in_buffer: 2
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/SAE_2025_04_02_32_15360_15/sae_training_iter_0/final
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/noelia_ft_dms/sae_15/
  resuming: true
  n_iters: 20
  model_diffing: true
