paths:
  model_path: "/home/woody/b114cb/b114cb23/models/model-3.2.1.1/"
  df_path: "/home/woody/b114cb/b114cb23/boxo/noelia_ft_dms/seq_gen/activity_predictions_no_penalty.csv"
  sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/noelia_ft_dms/diffing/
  top_features_path: ""
  out_dir: "/home/woody/b114cb/b114cb23/boxo/noelia_ft_dms/steering/M0_D0"

label: 3.2.1.1
model_iteration: 0 # 0
data_iteration: 0 # 0