base_config: base_config_alex_new.yaml

base:
  model_path: /home/woody/b114cb/b114cb23/DPO_amylase_run_SAPI_FT_v2/output_iteration3
sae:
  layer: 15

training:
  dataset_path: /home/woody/b114cb/b114cb23/boxo/dpo_noelia/joined_datasets/dataset_model_3
  name: "Diffing_SAPI_M3_D3_layer_15"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 450000
  threshold_num_batches: 5
  num_batches_in_buffer: 5 
  lr: 0.0003
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/noelia_ft_dms/sae_15/diffing/
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/dpo_noelia/M3_D3_rl2_layer_15/
  resuming: true
  model_diffing: true
