
base_config: base_config_workstation.yaml
base:
  model_path: AI4PD/ZymCTRL 
  d_sae: 10240

training:
  num_tokens: 50000
  name: "sae_training_iter_0"
  checkpoint_dir: /users/nferruz/gboxo/ZymCTRL/checkpoints/sae_training_iter_0
  
resuming:
  resume_from: 
  resuming: false
  checkpoint_dir_to: /users/nferruz/gboxo/ZymCTRL/checkpoints/sae_training_iter_0
  wandb_project: "DEBUG"

