paths:
  seqs_path: /home/woody/b114cb/b114cb23/boxo/strong_steering/latent_scoring_base_o2/ablation_with_all/M0_D0_94_0.02/
  output_path: /home/woody/b114cb/b114cb23/boxo/strong_steering/latent_scoring_base_o2/ablation_with_all/M0_D0_94_0.02//activity_predictions_lr.csv
  oracle_path1: "/home/woody/b114cb/b114cb23/models/esm2_t33_650M_UR50D"
label: 3.2.1.1
