  paths:
    model_path: /home/woody/b114cb/b114cb23/DPO_clean_amylase_run_SAPI_only_gerard/output_iteration20
    sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/diffing_sapi_multi_iterations_clean/M4_D4/diffing/
    out_dir: /home/woody/b114cb/b114cb23/boxo/diffing_sapi_multi_iterations_clean/latent_scoring/latent_scoring_4/
    cs_path: "/home/woody/b114cb/b114cb23/boxo/diffing_sapi_multi_iterations_clean/cs_data/all_cs.pt"
    df_path: "/home/woody/b114cb/b114cb23/boxo/diffing_sapi_multi_iterations_clean/joined_dataframes/dataframe_all_iteration{iteration_num}.csv"

  iteration_num: 4 
  label: 3.2.1.1
  model_iteration: 4
  data_iteration: 4 
  thresholds:
    pred: 
      upper: 2 
      lower: 1
    plddt: 
      upper: 0.7
      lower: 0.5
    tm_score: 
      upper: 0.65
      lower: 0.55

