base:
  seed: 42
  model_name: ZymCTRL
  model_path: AI4PD/ZymCTRL
sae:
  model_type: BatchTopKSAE
  site: resid_pre
  layer: 26
  act_size: 1280
  dict_size: 10240
  input_unit_norm: true
  device: "cuda:0"
  dtype: "float32"

training:
  dataset_path: /users/nferruz/gboxo/ZymCTRL_Dataset/final_dataset_big/
  batch_size: 128
  model_batch_size: 64 
  lr: 0.001
  num_tokens: 1000000000
  l1_coeff: 0
  beta1: 0.9
  beta2: 0.999
  max_grad_norm: 100000
  seq_len: 256
  use_wandb: true
  n_batches_to_dead: 5
  checkpoint_dir: /users/nferruz/gboxo/ZymCTRL/checkpoints/ZymCTRL_25_02_25_h100_blocks.26.hook_resid_pre_10240_batchtopk_100_0.0003_200000
  wandb_dir: /users/nferruz/gboxo/wandb/
  top_k: 100  
  top_k_aux: 512 
  aux_penalty: 0.01
  bandwidth: 0.001
  name: "SAE_Training" 
  threshold_compute_freq: 1000
  threshold_num_batches: 50
  num_batches_in_buffer: 20
  perf_log_freq: 1000
  checkpoint_freq: 10000
  wandb_project: "ZymCTRL_SAE"

resuming:
  resume_from: /users/nferruz/gboxo/ZymCTRL/checkpoints/
  checkpoint_dir_to: /users/nferruz/gboxo/ZymCTRL/checkpoints/
  resuming: false
  n_iters: 0
  model_diffing: false

