base_config: base_config_workstation.yaml

base:
  model_path: AI4PD/ZymCTRL 
training:
  dataset_path: /users/nferruz/gboxo/crg_boxo/Data/Diffing Alpha Amylase/tokenized_train_dataset_iteration0
  name: "Model_Diffing_M0_D0"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 2000000

resuming:
  resume_from: /users/nferruz/gboxo/ZymCTRL/checkpoints/ZymCTRL_25_02_25_h100_blocks.26.hook_resid_pre_10240_batchtopk_100_0.0003_200000
  checkpoint_dir_to: /users/nferruz/gboxo/ZymCTRL/checkpoints/Diffing Alpha Amylase/M0_D0
  resuming: true
  n_iters: 700
  model_diffing: true
