base_config: base_config_workstation.yaml

base:
  model_path: AI4PD/ZymCTRL 
training:
  dataset_path: /users/nferruz/gboxo/crg_boxo/Data/Diffing Alpha Amylase/tokenized_train_dataset_iteration7
  name: "Model_Diffing_M0_D7"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 2000000

resuming:
  resume_from: /users/nferruz/gboxo/ZymCTRL/checkpoints/Diffing Alpha Amylase/M0_D6/diffing
  checkpoint_dir_to: /users/nferruz/gboxo/ZymCTRL/checkpoints/Diffing Alpha Amylase/M0_D7
  resuming: true
  n_iters: 700
  model_diffing: true
