
base_config: base_config_alex.yaml
base:
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
  d_sae: 20480
  batch_size: 4096
  model_batch_size: 512 
  seq_len: 512

training:
  num_tokens: 50000
  name: "sae_training_iter_4"
  threshold_compute_freq: 1
  threshold_num_batches: 20 
  num_batches_in_buffer: 3 
  perf_log_freq: 1
  checkpoint_freq: 10
  datset_path: /home/woody/b114cb/b114cb23/boxo/new_dataset_train/
  
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_training_iter_3/final
  resuming: true
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_training_iter_4
