base:
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
  d_sae: 1280

training:
  num_tokens: 1000000
  name: "sae_training_iter_0"
  
resuming:
  resume_from: 
  resuming: false
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/boxo/checkpoints/sae_training_iter_0
