
paths:
  output_dir: "/home/woody/b114cb/b114cb23/boxo/Diffing_Analysis_Data/"
  df_path: "/home/woody/b114cb/b114cb23/boxo/Diffing_Analysis_Data/dataframe_iteration{data_iteration}.csv"
  model_path: "/home/woody/b114cb/b114cb23/models/ZymCTRL/"
  sae_path: "/home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/New_SAE/sae_training_iter_0_32/final/"


iterations:
  iteration_num: 0
  model_iteration: 0
  data_iteration: 0

ec_label: "3.2.1.1"




