paths:
  output_dir: "/home/woody/b114cb/b114cb23/boxo/Diffing_Analysis_Data/"
  base_sae: "/home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/sae_training_iter_0_100/final/checkpoint_latest.pt"
  diffing_folder: "/home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/Diffing Alpha Amylase New/"
iterations:
  start: 0
  end: 5



