paths: 
  cs_path: "/home/woody/b114cb/b114cb23/boxo/Diffing_Analysis_Data/all_cs.pt"
  df_path: "/home/woody/b114cb/b114cb23/boxo/Diffing_Analysis_Data/dataframe_iteration{iteration_num}.csv"
  output_dir: "/home/woody/b114cb/b114cb23/boxo/Diffing_Analysis_Data"
  model_path: "/home/woody/b114cb/b114cb23/Filippo/Q4_2024/DPO/DPO_Clean/DPO_clean_alphamylase/output_iteration{iteration_num}/" 
  sae_path: "/home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/Diffing Alpha Amylase New/M{model_iteration}_D{data_iteration}/diffing/"

iteration_num: 0
label: 3.2.1.1
model_iteration: 0
data_iteration: 0
thresholds:
  pred1: 
    upper: 3
    lower: 1.5
  pred2: 
    upper: 1.5
    lower: 0
  plddt: 
    upper: 0.7
    lower: 0
  tm_score: 
    upper: 0.8
    lower: 0