    paths:
      model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
      sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/diffing_sapi_multi_iterations_clean/diffing/
      top_features_path: /home/woody/b114cb/b114cb23/boxo/diffing_sapi_multi_iterations_clean/latent_scoring/latent_scoring_0/important_features/important_features_neg_M0_D0.pkl
      out_dir: /home/woody/b114cb/b114cb23/boxo/diffing_sapi_multi_iterations_clean/clipping_with_all/importance/M0_D0_neg
    label: 3.2.1.1
    model_iteration: 0
    data_iteration: 0
