paths:
  seqs_path: /home/woody/b114cb/b114cb23/boxo/finetune_SAE_DMS/clipping_with_all/importance/M0_D0_pos
  output_path: /home/woody/b114cb/b114cb23/boxo/finetune_SAE_DMS/clipping_with_all/importance/M0_D0_pos/activity_predictions_pos.csv
  oracle_path1: "/home/woody/b114cb/b114cb23/models/esm2_t33_650M_UR50D"
  checkpoint_path1: "/home/woody/b114cb/b114cb23/Filippo/alpha_amylase_activity_predictor/LoRa_esm2_3B/esm_GB1_finetuned.pth"
  oracle_path2: "/home/woody/b114cb/b114cb23/models/esm1v_t33_650M_UR90S_1"
  checkpoint_path2: "/home/woody/b114cb/b114cb23/Filippo/alpha_amylase_activity_predictor/LoRA_esm1v/Esm1v_GB1_finetuned.pth"
label: 3.2.1.1
