base_config: base_config_alex.yaml

base:
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
training:
  dataset_path: /home/woody/b114cb/b114cb23/boxo/diffing_datasets/dataset_iteration12/
  name: "Model_Diffing_M0_D12"
  perf_log_freq: 1
  threshold_compute_freq: 1
  aux_penalty: 0
  top_k_aux: 0
  num_tokens: 400000
  threshold_num_batches: 5
  num_batches_in_buffer: 10
resuming:
  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/Diffing Alpha Amylase New/M0_D11/diffing
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/Diffing Alpha Amylase New/M0_D12
  resuming: true
  n_iters: 20
  model_diffing: true
