
base:
  seed: 42
  model_name: ZymCTRL
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
sae:
  model_type: BatchTopKSAE
  sae_type: BathcTopKSAE
  site: resid_pre
  layer: 26
  act_size: 1280
  dict_size: 10240
  input_unit_norm: true
  device: "cuda:0"
  dtype: "float32"

training:
  checkpoint_dir: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/
  wandb_dir: /home/woody/b114cb/b114cb23/boxo/
  dataset_path: /home/woody/b114cb23/boxo/final_dataset_big/
  num_tokens: 1000000000
  batch_size: 4096
  model_batch_size: 512 
  seq_len: 256
  lr: 0.001
  l1_coeff: 0
  beta1: 0.9
  beta2: 0.999
  max_grad_norm: 100000
  use_wandb: true
  n_batches_to_dead: 5
  wandb_project: "ZymCTRL_SAE"
  top_k: 100  
  top_k_aux: 512 
  aux_penalty: 0.01
  bandwidth: 0.001
  name: "SAE_Training" 
  threshold_compute_freq: 1000
  threshold_num_batches: 50
  num_batches_in_buffer: 20
  perf_log_freq: 1000
  checkpoint_freq: 10000

resuming:

  resume_from: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/
  resuming: false
  n_iters: 0
  resume_history: false
  model_diffing: false




