
base:
  seed: 42
  model_name: "default_model"
  model_path: "/path/to/default/model"

sae:
  model_type: "default_type"
  sae_type: "default_sae"
  site: "default_site"
  layer: "default_layer"
  act_size: 256
  dict_size: 512
  input_unit_norm: true
  device: "cpu"
  dtype: "float32"

training:
  dataset_path: "/path/to/default/dataset"
  batch_size: 64
  model_batch_size: 32
  lr: 0.001
  num_tokens: 10000
  l1_coeff: 0.1
  beta1: 0.9
  beta2: 0.999
  max_grad_norm: 1.0
  seq_len: 128
  checkpoint_path: "/path/to/default/checkpoint"
  use_wandb: false
  n_batches_to_dead: 1000
  checkpoint_dir: "/path/to/default/checkpoints"
  wandb_dir: "/path/to/default/wandb"
  top_k: 5
  top_k_aux: 3
  aux_penalty: 0.1
  bandwidth: 0.5
  hook_point: "default_hook"
  name: "default_experiment"
  config: "default"
  wandb_run_id: "default_id"
  threshold_compute_freq: 10
  threshold_num_batches: 50
  num_batches_in_buffer: 20
  perf_log_freq: 100
  checkpoint_freq: 10
  wandb_project: "default_project"

resuming:
  n_iters: 10000
  resume_from: "/path/to/default/resume"
  resume_history: false
