
    paths:
      model_path: /home/woody/b114cb/b114cb23/models/model-3.2.1.1/
      out_dir: /home/woody/b114cb/b114cb23/boxo/unified_experiments/ablation/importance/dms_model

    model_name: "dms_model" 
    label: 3.2.1.1
    n_samples: 10
    n_batches: 10

