
base_config: base_config_alex_new.yaml
base:
  model_path: /home/woody/b114cb/b114cb23/models/ZymCTRL/
  d_sae: 5120
  batch_size: 256
  model_batch_size: 128 
  seq_len: 256

training:
  checkpoint_dir: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/DEBUG/
  lr: 0.0005
  num_tokens: 200000000
  name: "debug_iter_0"
  max_grad_norm: 0.5
  threshold_compute_freq: 100
  threshold_num_batches: 20 
  num_batches_in_buffer: 1
  perf_log_freq: 100
  checkpoint_freq: 1000
  top_k: 32  
  top_k_aux: 512 
  aux_penalty: 0.031
  datset_path: /home/woody/b114cb/b114cb23/boxo/new_dataset_concat_train/
  
resuming:
  resume_from: 
  resuming: false
  checkpoint_dir_to: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/DEBUG/
