  paths:
    model_path: /home/woody/b114cb/b114cb23/DPO_clean_amylase_run_SAPI_only_gerard/output_iteration30/
    sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/diffing_sapi_07_04/M30_D30/diffing/
    out_dir: /home/woody/b114cb/b114cb23/boxo/diffing_sapi_07_04/latent_scoring/latent_scoring_30_rl/
    cs_path: "/home/woody/b114cb/b114cb23/boxo/diffing_sapi_07_04/cs_data/all_cs.pt"
    df_path: "/home/woody/b114cb/b114cb23/boxo/diffing_sapi_07_04/dataframes/dataframe_iteration{iteration_num}.csv"

  iteration_num: 30 
  label: 3.2.1.1
  model_iteration: 30
  data_iteration: 30 
  thresholds:
    pred: 
      upper: 2 
      lower: 1
    plddt: 
      upper: 0.7
      lower: 0.5
    tm_score: 
      upper: 0.65
      lower: 0.55

