paths:
  model_path: "/home/woody/b114cb/b114cb23/models/ZymCTRL/"
  df_path: "/home/woody/b114cb/b114cb23/boxo/finetune_SAE_DMS/dms_df.csv"
  sae_path: /home/woody/b114cb/b114cb23/ZymCTRLSAEs/checkpoints/finetune_SAE_DMS/diffing/
  top_features_path: ""
  out_dir: "/home/woody/b114cb/b114cb23/boxo/finetune_SAE_DMS/steering/steering/M1_D1_pos_new"

label: 3.2.1.1
model_iteration: 0 # 0
data_iteration: 0 # 0