paths:
  seqs_path: /home/woody/b114cb/b114cb23/boxo/strong_steering/latent_scoring_dms/latent_scoring_FT/ablation_with_all/M0_D0_96/
  output_path: /home/woody/b114cb/b114cb23/boxo/strong_steering/latent_scoring_dms/latent_scoring_FT/ablation_with_all/M0_D0_96//activity_predictions_lr.csv
  oracle_path1: "/home/woody/b114cb/b114cb23/models/esm1v_t33_650M_UR90S_1"
  checkpoint_path1: "/home/woody/b114cb/b114cb23/Filippo/alpha_amylase_activity_predictor/LoRA_esm1v/Esm1v_GB1_finetuned.pth"
label: 3.2.1.1
